# Generated by Django 2.2.5 on 2019-09-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
